### ROOM ###

# POST http://127.0.0.1:8080/api/rooms/
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "roomId": "B11222",
#   "userId": "A00006",
#   "minute": "3000",
#   "title": "Kelas Belajar B11222 Psychology",
#   "description": "Lorem B11222 ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "expired": true
# }

# GET http://127.0.0.1:8080/api/rooms/B00003
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/rooms/B00003
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "minute": "120",
#   "title": "Kelas Belajar Geography",
#   "description": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "expired": true
# }

# DELETE http://127.0.0.1:8080/api/rooms/B11222
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET http://127.0.0.1:8080/api/rooms
GET http://127.0.0.1:8080/api/rooms?size=3&page=0
X-Api-Key: utif.pages.dev
Accept: application/json

# PUT http://127.0.0.1:8080/api/rooms/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json
# Content-Type: application/json

# {
# }

# DELETE http://127.0.0.1:8080/api/rooms/A00004
# X-Api-Key: utif.pages.dev
# Accept: application/json

### USER ###

# POST http://127.0.0.1:8080/api/users/
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "userId": "A00012",
#   "fullName": "Nyelip dua",
#   "email": "dua@gmail.com",
#   "phone": "+62-812-7534-0012",
#   "username": "dua",
#   "password": "12121212"
# }

# GET http://127.0.0.1:8080/api/users/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json

# DELETE http://127.0.0.1:8080/api/users/A00004
# X-Api-Key: utif.pages.dev
# Accept: application/json

# GET http://127.0.0.1:8080/api/users?size=5&page=2
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/users/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json
# Content-Type: application/json

# {
#     "fullName": "Nyelip satu",
#       "email": "satu@gmail.com",
#       "phone": "+62-812-7534-0011",
#       "username": "satu",
#       "password": "12121212"
# }