
### Authentication ###
# POST https://who-knows-backend.herokuapp.com/api/auth/sign-in
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#     "email": "utifmd@gmail.com",
#     "password": "12121212"
# }

### PARTICIPANT ###

# POST https://who-knows-backend.herokuapp.com/api/participants
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "participantId": "P00002",
#   "roomId": "B00001",
#   "userId": "A00003",
#   "currentPage": "2",
#   "timeLeft": "25",
#   "expired": false
# }

# GET https://who-knows-backend.herokuapp.com/participants/
# X-Api-Key: utif.pages.dev
# Accept: application/json

# GET https://who-knows-backend.herokuapp.com/api/participants
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT https://who-knows-backend.herokuapp.com/api/participants/P00001
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "roomId": "B00001",
#   "userId": "A00002",
#   "currentPage": "2",
#   "timeLeft": "35",
#   "expired": false
# }

# DELETE https://who-knows-backend.herokuapp.com/api/participants/A00002
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET https://who-knows-backend.herokuapp.com/api/participants
# # GET https://who-knows-backend.herokuapp.com/api/participants?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

### RESULT ###

# POST https://who-knows-backend.herokuapp.com/api/results
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "resultId": "R00001",
#   "participantId": "P00001",
#   "roomId": "B00001",
#   "userId": "A00002",
#   "score": "85",
#   "correctQuiz": [
#         "Pertanyaan no 1, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#         "Pertanyaan no 3, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#         "Pertanyaan no 4, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#         "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique."
#       ],
#   "wrongQuiz": ["Pertanyaan no 2, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique."]
# }

# GET https://who-knows-backend.herokuapp.com/api/results/R00001
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT https://who-knows-backend.herokuapp.com/api/results/D00001
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 3",
#   "createdBy": "Utif Milkedori"
# }

# DELETE https://who-knows-backend.herokuapp.com/api/results/A00002
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET https://who-knows-backend.herokuapp.com/api/results
# # GET https://who-knows-backend.herokuapp.com/api/results?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

### QUIZ ###

# POST https://who-knows-backend.herokuapp.com/api/questions
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "quizId": "C00005",
#   "roomId": "B00001",
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 2",
#   "createdBy": "Utif Milkedori"
# }

# GET https://who-knows-backend.herokuapp.com/api/questions/C00002
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT https://who-knows-backend.herokuapp.com/api/questions/C00005
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 3",
#   "createdBy": "Utif Milkedori"
# }

# DELETE https://who-knows-backend.herokuapp.com/api/questions/A00002
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET https://who-knows-backend.herokuapp.com/api/questions
# # GET https://who-knows-backend.herokuapp.com/api/questions?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

### ROOM ###

# POST https://who-knows-backend.herokuapp.com/api/rooms/
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "roomId": "B00022",
#   "userId": "A00002",
#   "minute": "3000",
#   "title": "Kelas Belajar Accounting",
#   "description": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "expired": false
# }

# GET https://who-knows-backend.herokuapp.com/api/rooms/B00001
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT https://who-knows-backend.herokuapp.com/api/rooms/B00003
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "minute": "120",
#   "title": "Kelas Belajar Geography",
#   "description": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "expired": true
# }

# DELETE https://who-knows-backend.herokuapp.com/api/rooms/B11222
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET https://who-knows-backend.herokuapp.com/api/rooms
# GET https://who-knows-backend.herokuapp.com/api/rooms?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT https://who-knows-backend.herokuapp.com/api/rooms/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json
# Content-Type: application/json

# {
# }

# DELETE https://who-knows-backend.herokuapp.com/api/rooms/A00004
# X-Api-Key: utif.pages.dev
# Accept: application/json

### USER ###

# POST https://who-knows-backend.herokuapp.com/api/users/
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "userId": "A00012",
#   "fullName": "Nyelip dua",
#   "email": "dua@gmail.com",
#   "phone": "+62-812-7534-0012",
#   "username": "dua",
#   "password": "12121212"
# }

# GET https://who-knows-backend.herokuapp.com/api/users/A00001
# X-Api-Key: utif.pages.dev
# Accept: application/json

# DELETE https://who-knows-backend.herokuapp.com/api/users/A00004
# X-Api-Key: utif.pages.dev
# Accept: application/json

# GET https://who-knows-backend.herokuapp.com/api/users
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT https://who-knows-backend.herokuapp.com/api/users/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json
# Content-Type: application/json

# {
#     "fullName": "Nyelip satu",
#       "email": "satu@gmail.com",
#       "phone": "+62-812-7534-0011",
#       "username": "satu",
#       "password": "12121212"
# }