
### Authentication ###
# POST http://127.0.0.1:8080/api/auth/sign-in
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#     "email": "utifmd@gmail.com",
#     "password": "12121212"
# }

### PARTICIPANT ###

# POST http://127.0.0.1:8080/api/participants
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "participantId": "P00001",
#   "roomId": "B00001",
#   "userId": "A00002",
#   "currentPage": "1",
#   "timeLeft": "45",
#   "expired": false
# }

# Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae modi culpa, itaque esse voluptates saepe? Tempore fuga dignissimos ullam optio adipisci facilis doloribus vero nostrum nulla eius, dolorum quidem placeat.

# GET http://127.0.0.1:8080/api/participant/D00001
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/participants/P00001
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "roomId": "B00001",
#   "userId": "A00002",
#   "currentPage": "2",
#   "timeLeft": "35",
#   "expired": false
# }

# DELETE http://127.0.0.1:8080/api/participant/A00002
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET http://127.0.0.1:8080/api/participants
# # GET http://127.0.0.1:8080/api/participants?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

### RESULT ###

# POST http://127.0.0.1:8080/api/result
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "quizId": "D00001",
#   "roomId": "B00001",
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 2",
#   "createdBy": "Utif Milkedori"
# }µ

# GET http://127.0.0.1:8080/api/result/D00001
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/result/D00001
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 3",
#   "createdBy": "Utif Milkedori"
# }

# DELETE http://127.0.0.1:8080/api/result/A00002
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET http://127.0.0.1:8080/api/questions
# # GET http://127.0.0.1:8080/api/questions?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

### QUIZ ###

# POST http://127.0.0.1:8080/api/questions
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "quizId": "C00005",
#   "roomId": "B00001",
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 2",
#   "createdBy": "Utif Milkedori"
# }

# GET http://127.0.0.1:8080/api/questions/C00002
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/questions/C00005
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "images": ["http://image.com/1.png", "http://image.com/2.png"],
#   "question": "Pertanyaan no 5, lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "options": ["option 1", "option 2", "option 3"],
#   "answer": "option 3",
#   "createdBy": "Utif Milkedori"
# }

# DELETE http://127.0.0.1:8080/api/questions/A00002
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET http://127.0.0.1:8080/api/questions
# # GET http://127.0.0.1:8080/api/questions?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

### ROOM ###

# POST http://127.0.0.1:8080/api/rooms/
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "roomId": "B00022",
#   "userId": "A00002",
#   "minute": "3000",
#   "title": "Kelas Belajar Accounting",
#   "description": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "expired": false
# }

# GET http://127.0.0.1:8080/api/rooms/B00022
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/rooms/B00003
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "minute": "120",
#   "title": "Kelas Belajar Geography",
#   "description": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id aliquid dignissimos facere reiciendis ipsam praesentium cupiditate magnam facilis minus, ullam ex beatae sequi! Cupiditate ex pariatur aliquam, animi iure similique.",
#   "expired": true
# }

# DELETE http://127.0.0.1:8080/api/rooms/B11222
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# GET http://127.0.0.1:8080/api/rooms
# GET http://127.0.0.1:8080/api/rooms?size=3&page=0
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/rooms/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json
# Content-Type: application/json

# {
# }

# DELETE http://127.0.0.1:8080/api/rooms/A00004
# X-Api-Key: utif.pages.dev
# Accept: application/json

### USER ###

# POST http://127.0.0.1:8080/api/users/
# X-Api-Key: utif.pages.dev
# Content-Type: application/json
# Accept: application/json

# {
#   "userId": "A00012",
#   "fullName": "Nyelip dua",
#   "email": "dua@gmail.com",
#   "phone": "+62-812-7534-0012",
#   "username": "dua",
#   "password": "12121212"
# }

# GET http://127.0.0.1:8080/api/users/A00002
# X-Api-Key: utif.pages.dev
# Accept: application/json

# DELETE http://127.0.0.1:8080/api/users/A00004
# X-Api-Key: utif.pages.dev
# Accept: application/json

# GET http://127.0.0.1:8080/api/users?size=5&page=2
# X-Api-Key: utif.pages.dev
# Accept: application/json

# PUT http://127.0.0.1:8080/api/users/A00011
# X-Api-Key: utif.pages.dev
# Accept: application/json
# Content-Type: application/json

# {
#     "fullName": "Nyelip satu",
#       "email": "satu@gmail.com",
#       "phone": "+62-812-7534-0011",
#       "username": "satu",
#       "password": "12121212"
# }